# wrangler.toml - Cloudflare Worker Configuration
name = "socialhub-api"
main = "src/index.js"
compatibility_date = "2026-06-29"
account_id = "08f4a1647bc1230e867e4818b5aada0a"


# Variables/Bindings
[vars]
ENVIRONMENT = "production"
THREADS_CLIENT_ID = "952901221088471"
FACEBOOK_APP_ID = "1775553577131102"
INSTAGRAM_CLIENT_ID = "2829348337448437"
FRONTEND_ORIGIN = "https://socialhub.kwikezee.my"
OPENROUTER_MODEL = "@cf/meta/llama-3.2-3b-instruct"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "socialhub-db"
database_id = "f8054d30-59c2-4cdd-820c-ffe8eed91bf9"

[triggers]
crons = ["* * * * *"]

[ai]
binding = "AI"


